name = "musickit-app"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[dev]
ip = "0.0.0.0"
port = 8787
inspector_port = 9229

[assets]
directory = "dist"
not_found_handling = "single-page-application"
binding = "assets"
run_worker_first = ["/api/*"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

# -------------------------------------------------------------------
# production environment
# -------------------------------------------------------------------
[env.production]
name = "musickit-app-production"
workers_dev = false
preview_urls = false
routes = [{ pattern = "music.tkgstrator.work", custom_domain = true }]

[env.production.assets]
directory = "dist"
not_found_handling = "single-page-application"
binding = "assets"
run_worker_first = ["/api/*"]

[env.production.vars]
APPLE_MUSIC_TEAM_ID = "5Q94QJ7G98"
APPLE_MUSIC_KEY_ID = "68B6NWM78Z"
CF_ACCESS_CLIENT_ID = "cfdfd7d6e420692d0d5a04db0872e875.access"
PROXY_URL = "https://kanade-backend.tkgstrator.work"

# -------------------------------------------------------------------
# staging environment
# -------------------------------------------------------------------
[env.staging]
name = "musickit-app-staging"
workers_dev = true
preview_urls = true
routes = [{ pattern = "music-dev.tkgstrator.work", custom_domain = true }]

[env.staging.assets]
directory = "dist"
not_found_handling = "single-page-application"
binding = "assets"
run_worker_first = ["/api/*"]

[env.staging.vars]
APPLE_MUSIC_TEAM_ID = "5Q94QJ7G98"
APPLE_MUSIC_KEY_ID = "68B6NWM78Z"
CF_ACCESS_CLIENT_ID = "cfdfd7d6e420692d0d5a04db0872e875.access"
PROXY_URL = "https://kanade-backend.tkgstrator.work"
