/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as ArtistsIndexRouteImport } from './routes/artists/index'
import { Route as AlbumsIndexRouteImport } from './routes/albums/index'
import { Route as ArtistsArtist_idRouteImport } from './routes/artists/$artist_id'
import { Route as AlbumsAlbum_idRouteImport } from './routes/albums/$album_id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtist_idRoute = ArtistsArtist_idRouteImport.update({
  id: '/artists/$artist_id',
  path: '/artists/$artist_id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbum_idRoute = AlbumsAlbum_idRouteImport.update({
  id: '/albums/$album_id',
  path: '/albums/$album_id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums/$album_id': typeof AlbumsAlbum_idRoute
  '/artists/$artist_id': typeof ArtistsArtist_idRoute
  '/albums/': typeof AlbumsIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums/$album_id': typeof AlbumsAlbum_idRoute
  '/artists/$artist_id': typeof ArtistsArtist_idRoute
  '/albums': typeof AlbumsIndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/search': typeof SearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums/$album_id': typeof AlbumsAlbum_idRoute
  '/artists/$artist_id': typeof ArtistsArtist_idRoute
  '/albums/': typeof AlbumsIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums/$album_id'
    | '/artists/$artist_id'
    | '/albums/'
    | '/artists/'
    | '/search/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums/$album_id'
    | '/artists/$artist_id'
    | '/albums'
    | '/artists'
    | '/search'
  id:
    | '__root__'
    | '/'
    | '/albums/$album_id'
    | '/artists/$artist_id'
    | '/albums/'
    | '/artists/'
    | '/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsAlbum_idRoute: typeof AlbumsAlbum_idRoute
  ArtistsArtist_idRoute: typeof ArtistsArtist_idRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$artist_id': {
      id: '/artists/$artist_id'
      path: '/artists/$artist_id'
      fullPath: '/artists/$artist_id'
      preLoaderRoute: typeof ArtistsArtist_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$album_id': {
      id: '/albums/$album_id'
      path: '/albums/$album_id'
      fullPath: '/albums/$album_id'
      preLoaderRoute: typeof AlbumsAlbum_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsAlbum_idRoute: AlbumsAlbum_idRoute,
  ArtistsArtist_idRoute: ArtistsArtist_idRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
