name: Deploy to Cloudflare Workers
on:
  pull_request:
    branches:
      - develop
      - master
    types: [closed]
jobs:
  deploy:
    name: Deploy workers
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Set environment
        run: |
          echo "ENVIRONMENT=$(if [[ '${{ github.event.pull_request.base.ref }}' == '${{ github.event.repository.default_branch }}' ]]; then echo 'production'; else echo 'staging'; fi)" >> $GITHUB_ENV
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
        env:
          CLOUDFLARE_ENV: ${{ env.ENVIRONMENT }}
      - name: Wrangler deploy
        uses: cloudflare/wrangler-action@v3
        env:
          ENVIRONMENT: ${{ github.event.pull_request.base.ref == 'master' && 'production' || 'staging' }}
        with:
          wranglerVersion: latest
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env ${{ env.ENVIRONMENT }} --minify src/index.ts
